// mockData.js
import {
    Users,
    Cpu,
    BookOpen,
    MessageCircle,
    Settings,
    Share2,
    Shield,
    Film,
    Music,
    LoaderPinwheel,
    Gamepad2,
    Book,
    CheckCheck,
    UserPlus,
    Heart,
    ThumbsUp,
    Bell,
    Star,
    AlertTriangle,
    Gift,
    Activity,
    Calendar,
  } from "lucide-react-native";
  
  // User data type
  export const users = [
    {
      id: 1,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: true,
      name: "John Farmer",
      lastMessage: "Harvest season is coming up fast!",
      timestamp: "5 min",
      unreadMessages: 4,
    },
    {
      id: 2,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: false,
      name: "Mary Greenfield",
      lastMessage: "Did you hear about the new irrigation system?",
      timestamp: "10 min",
      unreadMessages: 2,
    },
    {
      id: 3,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: true,
      name: "David Fields",
      lastMessage: "The soil tests came back positive!",
      timestamp: "15 min",
      unreadMessages: 1,
    },
    {
      id: 4,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: false,
      name: "Laura Meadows",
      lastMessage: "Let's discuss the upcoming livestock auction.",
      timestamp: "20 min",
      unreadMessages: 3,
    },
    {
      id: 5,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: true,
      name: "Peter Orchard",
      lastMessage: "We need to order more fertilizer.",
      timestamp: "25 min",
      unreadMessages: 0,
    },
    {
      id: 6,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: true,
      name: "Sarah Vineyard",
      lastMessage: "The grape harvest looks promising this year!",
      timestamp: "30 min",
      unreadMessages: 5,
    },
    {
      id: 7,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: false,
      name: "Mark Croft",
      lastMessage: "Thanks for the tips on organic farming.",
      timestamp: "35 min",
      unreadMessages: 0,
    },
    {
      id: 8,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: true,
      name: "Anna Mill",
      lastMessage: "Can you help me with the crop rotation plan?",
      timestamp: "40 min",
      unreadMessages: 7,
    },
    {
      id: 9,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: false,
      name: "Michael Grove",
      lastMessage: "Let's schedule a meeting to discuss the harvest logistics.",
      timestamp: "45 min",
      unreadMessages: 1,
    },
    {
      id: 10,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: true,
      name: "Emily Field",
      lastMessage: "The wheat fields are looking golden!",
      timestamp: "50 min",
      unreadMessages: 2,
    },
    {
      id: 11,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: false,
      name: "Jack Arbor",
      lastMessage: "I planted a new batch of apple trees.",
      timestamp: "55 min",
      unreadMessages: 4,
    },
    {
      id: 12,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: true,
      name: "Sophie Grove",
      lastMessage: "The orchard is in bloom!",
      timestamp: "1 hour",
      unreadMessages: 3,
    },
    {
      id: 13,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: false,
      name: "Henry Fields",
      lastMessage: "We should check the weather forecast for planting.",
      timestamp: "1 hour 5 min",
      unreadMessages: 2,
    },
    {
      id: 14,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: true,
      name: "Emma Rancher",
      lastMessage: "The cattle market is looking good.",
      timestamp: "1 hour 10 min",
      unreadMessages: 0,
    },
    {
      id: 15,
      profilePicture: "https://i.pravatar.cc/300",
      isOnline: false,
      name: "James Meadows",
      lastMessage: "Preparing for the next planting season.",
      timestamp: "1 hour 15 min",
      unreadMessages: 6,
    },
  ];
  // Group data type
  export const groups = [
    {
      id: 1,
      Icon: CheckCheck,
      color: "#FF9500",
      groupName: "React Native",
      description: "A group for React Native enthusiasts to discuss and share ideas. Join us to explore the latest features, share projects, and improve your skills in building cross-platform applications.",
      membersCount: 55,
      followersCount: 136,
      followersIncluding: "@nexendk",
      avatars: [
        "https://i.pravatar.cc/300?img=1",
        "https://i.pravatar.cc/300?img=2",
        "https://i.pravatar.cc/300?img=3",
        "https://i.pravatar.cc/300?img=4",
        "https://i.pravatar.cc/300?img=5",
      ],
      timestamp: "90 mins",
    },
    {
      id: 2,
      Icon: CheckCheck,
      color: "#FF9500",
      groupName: "Flutter Devs",
      description: "Join us to discuss everything Flutter. Whether you're a beginner or an expert, share your knowledge, get tips, and stay updated with the latest in Flutter development.",
      membersCount: 42,
      followersCount: 200,
      followersIncluding: "@flutteruser",
      avatars: [
        "https://i.pravatar.cc/300?img=6",
        "https://i.pravatar.cc/300?img=7",
        "https://i.pravatar.cc/300?img=8",
        "https://i.pravatar.cc/300?img=9",
        "https://i.pravatar.cc/300?img=10",
      ],
      timestamp: "60 mins",
    },
    {
      id: 3,
      groupName: "Kotlin Enthusiasts",
      description: "All about Kotlin programming language. Discuss best practices, share code snippets, and learn how Kotlin can make your development process smoother and more enjoyable.",
      membersCount: 30,
      followersCount: 120,
      followersIncluding: "@kotlinfan",
      avatars: [
        "https://i.pravatar.cc/300?img=11",
        "https://i.pravatar.cc/300?img=12",
        "https://i.pravatar.cc/300?img=13",
        "https://i.pravatar.cc/300?img=14",
        "https://i.pravatar.cc/300?img=15",
      ],
      timestamp: "120 mins",
    },
    {
      id: 4,
      groupName: "Swift Developers",
      description: "Connect with other Swift developers. Share your experiences, get help with coding issues, and stay up-to-date with the latest developments in the Swift programming language.",
      membersCount: 50,
      followersCount: 150,
      followersIncluding: "@swiftdev",
      avatars: [
        "https://i.pravatar.cc/300?img=16",
        "https://i.pravatar.cc/300?img=17",
        "https://i.pravatar.cc/300?img=18",
        "https://i.pravatar.cc/300?img=19",
        "https://i.pravatar.cc/300?img=20",
      ],
      timestamp: "2 hours",
    },
    {
      id: 5,
      groupName: "JavaScript Masters",
      description: "A place for JavaScript masters to share knowledge. Engage in deep discussions, explore advanced topics, and enhance your expertise in JavaScript development.",
      membersCount: 80,
      followersCount: 250,
      followersIncluding: "@jspro",
      avatars: [
        "https://i.pravatar.cc/300?img=21",
        "https://i.pravatar.cc/300?img=22",
        "https://i.pravatar.cc/300?img=23",
        "https://i.pravatar.cc/300?img=24",
        "https://i.pravatar.cc/300?img=25",
      ],
      timestamp: "3 hours",
    },
    {
      id: 6,
      groupName: "Python Programmers",
      description: "Discuss Python programming with peers. Share your projects, ask questions, and collaborate with other Python enthusiasts to improve your coding skills.",
      membersCount: 65,
      followersCount: 230,
      followersIncluding: "@pythonguru",
      avatars: [
        "https://i.pravatar.cc/300?img=26",
        "https://i.pravatar.cc/300?img=27",
        "https://i.pravatar.cc/300?img=28",
        "https://i.pravatar.cc/300?img=29",
        "https://i.pravatar.cc/300?img=30",
      ],
      timestamp: "4 hours",
    },
    {
      id: 7,
      groupName: "Ruby on Rails",
      description: "Join the Ruby on Rails community. Learn from experienced developers, share your insights, and stay updated with the latest trends and tools in the Ruby on Rails ecosystem.",
      membersCount: 40,
      followersCount: 140,
      followersIncluding: "@rubyonrailsdev",
      avatars: [
        "https://i.pravatar.cc/300?img=31",
        "https://i.pravatar.cc/300?img=32",
        "https://i.pravatar.cc/300?img=33",
        "https://i.pravatar.cc/300?img=34",
        "https://i.pravatar.cc/300?img=35",
      ],
      timestamp: "5 hours",
    },
    {
      id: 8,
      groupName: "Data Science",
      description: "A group for data science enthusiasts to share knowledge, discuss projects, and stay updated with the latest trends in data science and machine learning.",
      membersCount: 75,
      followersCount: 220,
      followersIncluding: "@datascientist",
      avatars: [
        "https://i.pravatar.cc/300?img=36",
        "https://i.pravatar.cc/300?img=37",
        "https://i.pravatar.cc/300?img=38",
        "https://i.pravatar.cc/300?img=39",
        "https://i.pravatar.cc/300?img=40",
      ],
      timestamp: "6 hours",
    },
  ];
  // Notification data type
  export const notifications = [
    {
      id: 1,
      Icon: Cpu,
      content: "System maintenance scheduled for 2 AM.",
      timestamp: "5 mins ago",
    },
    {
      id: 2,
      Icon: BookOpen,
      content: "New course available: Advanced React.",
      timestamp: "10 mins ago",
    },
    {
      id: 3,
      Icon: MessageCircle,
      content: "You have 3 new messages.",
      timestamp: "15 mins ago",
    },
    {
      id: 4,
      Icon: Settings,
      content: "Your settings have been updated.",
      timestamp: "20 mins ago",
    },
    {
      id: 5,
      Icon: Share2,
      content: "Your post has been shared 10 times.",
      timestamp: "25 mins ago",
    },
    {
      id: 6,
      Icon: Shield,
      content: "Security alert: Unusual login activity detected.",
      timestamp: "30 mins ago",
    },
    {
      id: 7,
      Icon: Film,
      content: "New video uploaded: Introduction to React Native.",
      timestamp: "35 mins ago",
    },
    {
      id: 8,
      Icon: Music,
      content: "Playlist updated: Top Coding Music.",
      timestamp: "40 mins ago",
    },
    {
      id: 9,
      Icon: LoaderPinwheel,
      content: "Your deployment is in progress.",
      timestamp: "45 mins ago",
    },
    {
      id: 10,
      Icon: Gamepad2,
      content: "New game released: CodeWars.",
      timestamp: "50 mins ago",
    },
    {
      id: 11,
      Icon: Book,
      content: "New blog post: Mastering Redux Toolkit.",
      timestamp: "55 mins ago",
    },
    {
      id: 12,
      Icon: CheckCheck,
      content: "Your task 'Update Documentation' is complete.",
      timestamp: "1 hour ago",
    },
    {
      id: 13,
      Icon: UserPlus,
      content: "You have a new follower: @nexendk.",
      timestamp: "1 hour 5 mins ago",
    },
    {
      id: 14,
      Icon: Heart,
      content: "Your post received 100 likes.",
      timestamp: "1 hour 10 mins ago",
    },
    {
      id: 15,
      Icon: ThumbsUp,
      content: "Your comment was upvoted.",
      timestamp: "1 hour 15 mins ago",
    },
    {
      id: 16,
      Icon: Bell,
      content: "Reminder: Team meeting at 3 PM.",
      timestamp: "1 hour 20 mins ago",
    },
    {
      id: 17,
      Icon: Star,
      content: "You earned a new badge: React Pro.",
      timestamp: "1 hour 25 mins ago",
    },
    {
      id: 18,
      Icon: AlertTriangle,
      content: "Warning: Disk space running low.",
      timestamp: "1 hour 30 mins ago",
    },
    {
      id: 19,
      Icon: Gift,
      content: "You received a gift: 1 month free subscription.",
      timestamp: "1 hour 35 mins ago",
    },
    {
      id: 20,
      Icon: Activity,
      content: "Your activity report is ready.",
      timestamp: "1 hour 40 mins ago",
    },
    {
      id: 21,
      Icon: Calendar,
      content: "Event scheduled: Hackathon on Saturday.",
      timestamp: "1 hour 45 mins ago",
    },
  ];
  
  
